name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag simchabi/webapp-new:${{github.run_number}}-${{github.sha}}
    - name: docker login
      run: docker login -u $ {{secrets.USERNAME}} -p {{secrets.PASS}}
    - name: Push the docker image
      run: docker push simchabi/webapp-new:${{github.run_number}}-${{github.sha}}
      
